package model.database.pojo;
// Generated Apr 19, 2018 11:52:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Coach generated by hbm2java
 */
public class Coach  implements java.io.Serializable {


     private Integer coachId;
     private String coachName;
     private String numberPlate;
     private String coachDescription;
     private Date modifiedDate;
     private byte numberOfSeats;
     private byte isOnTrip;
     private Set<Seat> seats = new HashSet<Seat>(0);
     private Set<CoachDriverTrip> coachDriverTrips = new HashSet<CoachDriverTrip>(0);

    public Coach() {
    }

	
    public Coach(String coachName, String numberPlate, Date modifiedDate, byte numberOfSeats, byte isOnTrip) {
        this.coachName = coachName;
        this.numberPlate = numberPlate;
        this.modifiedDate = modifiedDate;
        this.numberOfSeats = numberOfSeats;
        this.isOnTrip = isOnTrip;
    }
    public Coach(String coachName, String numberPlate, String coachDescription, Date modifiedDate, byte numberOfSeats, byte isOnTrip, Set<Seat> seats, Set<CoachDriverTrip> coachDriverTrips) {
       this.coachName = coachName;
       this.numberPlate = numberPlate;
       this.coachDescription = coachDescription;
       this.modifiedDate = modifiedDate;
       this.numberOfSeats = numberOfSeats;
       this.isOnTrip = isOnTrip;
       this.seats = seats;
       this.coachDriverTrips = coachDriverTrips;
    }
   
    public Integer getCoachId() {
        return this.coachId;
    }
    
    public void setCoachId(Integer coachId) {
        this.coachId = coachId;
    }
    public String getCoachName() {
        return this.coachName;
    }
    
    public void setCoachName(String coachName) {
        this.coachName = coachName;
    }
    public String getNumberPlate() {
        return this.numberPlate;
    }
    
    public void setNumberPlate(String numberPlate) {
        this.numberPlate = numberPlate;
    }
    public String getCoachDescription() {
        return this.coachDescription;
    }
    
    public void setCoachDescription(String coachDescription) {
        this.coachDescription = coachDescription;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public byte getNumberOfSeats() {
        return this.numberOfSeats;
    }
    
    public void setNumberOfSeats(byte numberOfSeats) {
        this.numberOfSeats = numberOfSeats;
    }
    public byte getIsOnTrip() {
        return this.isOnTrip;
    }
    
    public void setIsOnTrip(byte isOnTrip) {
        this.isOnTrip = isOnTrip;
    }
    public Set<Seat> getSeats() {
        return this.seats;
    }
    
    public void setSeats(Set<Seat> seats) {
        this.seats = seats;
    }
    public Set<CoachDriverTrip> getCoachDriverTrips() {
        return this.coachDriverTrips;
    }
    
    public void setCoachDriverTrips(Set<CoachDriverTrip> coachDriverTrips) {
        this.coachDriverTrips = coachDriverTrips;
    }




}


