package model.database.pojo;
// Generated Apr 19, 2018 11:52:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private Integer countryId;
     private String countryName;
     private Date modifiedDate;
     private Set<Cityordistrict> cityordistricts = new HashSet<Cityordistrict>(0);

    public Country() {
    }

	
    public Country(String countryName, Date modifiedDate) {
        this.countryName = countryName;
        this.modifiedDate = modifiedDate;
    }
    public Country(String countryName, Date modifiedDate, Set<Cityordistrict> cityordistricts) {
       this.countryName = countryName;
       this.modifiedDate = modifiedDate;
       this.cityordistricts = cityordistricts;
    }
   
    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set<Cityordistrict> getCityordistricts() {
        return this.cityordistricts;
    }
    
    public void setCityordistricts(Set<Cityordistrict> cityordistricts) {
        this.cityordistricts = cityordistricts;
    }




}


