package model.database.pojo;
// Generated Apr 13, 2018 3:52:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer customerId;
     private String customerName;
     private String customerPhoneNumber;
     private String customerEmail;
     private Date customerDateOfBirth;
     private String customerAddress;
     private Date modifiedDate;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public Customer() {
    }

	
    public Customer(String customerName, String customerPhoneNumber, Date modifiedDate) {
        this.customerName = customerName;
        this.customerPhoneNumber = customerPhoneNumber;
        this.modifiedDate = modifiedDate;
    }
    public Customer(String customerName, String customerPhoneNumber, String customerEmail, Date customerDateOfBirth, String customerAddress, Date modifiedDate, Set<Invoice> invoices) {
       this.customerName = customerName;
       this.customerPhoneNumber = customerPhoneNumber;
       this.customerEmail = customerEmail;
       this.customerDateOfBirth = customerDateOfBirth;
       this.customerAddress = customerAddress;
       this.modifiedDate = modifiedDate;
       this.invoices = invoices;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getCustomerPhoneNumber() {
        return this.customerPhoneNumber;
    }
    
    public void setCustomerPhoneNumber(String customerPhoneNumber) {
        this.customerPhoneNumber = customerPhoneNumber;
    }
    public String getCustomerEmail() {
        return this.customerEmail;
    }
    
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }
    public Date getCustomerDateOfBirth() {
        return this.customerDateOfBirth;
    }
    
    public void setCustomerDateOfBirth(Date customerDateOfBirth) {
        this.customerDateOfBirth = customerDateOfBirth;
    }
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


