package model.database.pojo;
// Generated Apr 11, 2018 12:54:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer invoiceId;
     private Specialpromotion specialpromotion;
     private Users users;
     private Date invoiceDueDate;
     private float totalPrice;
     private String description;
     private Date modifiedDate;
     private String invoiceStatus;
     private Set<Usertriplog> usertriplogs = new HashSet<Usertriplog>(0);
     private Set<Invoicelineitem> invoicelineitems = new HashSet<Invoicelineitem>(0);

    public Invoice() {
    }

	
    public Invoice(Users users, Date invoiceDueDate, float totalPrice, Date modifiedDate, String invoiceStatus) {
        this.users = users;
        this.invoiceDueDate = invoiceDueDate;
        this.totalPrice = totalPrice;
        this.modifiedDate = modifiedDate;
        this.invoiceStatus = invoiceStatus;
    }
    public Invoice(Specialpromotion specialpromotion, Users users, Date invoiceDueDate, float totalPrice, String description, Date modifiedDate, String invoiceStatus, Set<Usertriplog> usertriplogs, Set<Invoicelineitem> invoicelineitems) {
       this.specialpromotion = specialpromotion;
       this.users = users;
       this.invoiceDueDate = invoiceDueDate;
       this.totalPrice = totalPrice;
       this.description = description;
       this.modifiedDate = modifiedDate;
       this.invoiceStatus = invoiceStatus;
       this.usertriplogs = usertriplogs;
       this.invoicelineitems = invoicelineitems;
    }
   
    public Integer getInvoiceId() {
        return this.invoiceId;
    }
    
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }
    public Specialpromotion getSpecialpromotion() {
        return this.specialpromotion;
    }
    
    public void setSpecialpromotion(Specialpromotion specialpromotion) {
        this.specialpromotion = specialpromotion;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getInvoiceDueDate() {
        return this.invoiceDueDate;
    }
    
    public void setInvoiceDueDate(Date invoiceDueDate) {
        this.invoiceDueDate = invoiceDueDate;
    }
    public float getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(float totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getInvoiceStatus() {
        return this.invoiceStatus;
    }
    
    public void setInvoiceStatus(String invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }
    public Set<Usertriplog> getUsertriplogs() {
        return this.usertriplogs;
    }
    
    public void setUsertriplogs(Set<Usertriplog> usertriplogs) {
        this.usertriplogs = usertriplogs;
    }
    public Set<Invoicelineitem> getInvoicelineitems() {
        return this.invoicelineitems;
    }
    
    public void setInvoicelineitems(Set<Invoicelineitem> invoicelineitems) {
        this.invoicelineitems = invoicelineitems;
    }




}


