package model.database.pojo;
// Generated Apr 19, 2018 11:52:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Line generated by hbm2java
 */
public class Line  implements java.io.Serializable {


     private Integer lineId;
     private Station stationByDepartureStationId;
     private Station stationByDestinationStationId;
     private String lineName;
     private String lineDescription;
     private Date modifiedDate;
     private Set<Trip> trips = new HashSet<Trip>(0);

    public Line() {
    }

	
    public Line(Station stationByDepartureStationId, Station stationByDestinationStationId, String lineName, Date modifiedDate) {
        this.stationByDepartureStationId = stationByDepartureStationId;
        this.stationByDestinationStationId = stationByDestinationStationId;
        this.lineName = lineName;
        this.modifiedDate = modifiedDate;
    }
    public Line(Station stationByDepartureStationId, Station stationByDestinationStationId, String lineName, String lineDescription, Date modifiedDate, Set<Trip> trips) {
       this.stationByDepartureStationId = stationByDepartureStationId;
       this.stationByDestinationStationId = stationByDestinationStationId;
       this.lineName = lineName;
       this.lineDescription = lineDescription;
       this.modifiedDate = modifiedDate;
       this.trips = trips;
    }
   
    public Integer getLineId() {
        return this.lineId;
    }
    
    public void setLineId(Integer lineId) {
        this.lineId = lineId;
    }
    public Station getStationByDepartureStationId() {
        return this.stationByDepartureStationId;
    }
    
    public void setStationByDepartureStationId(Station stationByDepartureStationId) {
        this.stationByDepartureStationId = stationByDepartureStationId;
    }
    public Station getStationByDestinationStationId() {
        return this.stationByDestinationStationId;
    }
    
    public void setStationByDestinationStationId(Station stationByDestinationStationId) {
        this.stationByDestinationStationId = stationByDestinationStationId;
    }
    public String getLineName() {
        return this.lineName;
    }
    
    public void setLineName(String lineName) {
        this.lineName = lineName;
    }
    public String getLineDescription() {
        return this.lineDescription;
    }
    
    public void setLineDescription(String lineDescription) {
        this.lineDescription = lineDescription;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set<Trip> getTrips() {
        return this.trips;
    }
    
    public void setTrips(Set<Trip> trips) {
        this.trips = trips;
    }




}


