package model.database.pojo;
// Generated Apr 19, 2018 11:52:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tripstatus generated by hbm2java
 */
public class Tripstatus  implements java.io.Serializable {


     private int tripId;
     private Trip trip;
     private String tripStatus;
     private String description;
     private Date modifiedDate;

    public Tripstatus() {
    }

    public Tripstatus(Trip trip, String tripStatus, String description, Date modifiedDate) {
       this.trip = trip;
       this.tripStatus = tripStatus;
       this.description = description;
       this.modifiedDate = modifiedDate;
    }
   
    public int getTripId() {
        return this.tripId;
    }
    
    public void setTripId(int tripId) {
        this.tripId = tripId;
    }
    public Trip getTrip() {
        return this.trip;
    }
    
    public void setTrip(Trip trip) {
        this.trip = trip;
    }
    public String getTripStatus() {
        return this.tripStatus;
    }
    
    public void setTripStatus(String tripStatus) {
        this.tripStatus = tripStatus;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


