package model.database.pojo;
// Generated Apr 11, 2018 12:54:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Userpaymentinfo generated by hbm2java
 */
public class Userpaymentinfo  implements java.io.Serializable {


     private int userId;
     private Users users;
     private String cardholderName;
     private byte[] cardholderNumber;
     private Date expirationDate;
     private byte[] securityCode;
     private Date modifiedDate;

    public Userpaymentinfo() {
    }

    public Userpaymentinfo(Users users, String cardholderName, byte[] cardholderNumber, Date expirationDate, byte[] securityCode, Date modifiedDate) {
       this.users = users;
       this.cardholderName = cardholderName;
       this.cardholderNumber = cardholderNumber;
       this.expirationDate = expirationDate;
       this.securityCode = securityCode;
       this.modifiedDate = modifiedDate;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCardholderName() {
        return this.cardholderName;
    }
    
    public void setCardholderName(String cardholderName) {
        this.cardholderName = cardholderName;
    }
    public byte[] getCardholderNumber() {
        return this.cardholderNumber;
    }
    
    public void setCardholderNumber(byte[] cardholderNumber) {
        this.cardholderNumber = cardholderNumber;
    }
    public Date getExpirationDate() {
        return this.expirationDate;
    }
    
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }
    public byte[] getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(byte[] securityCode) {
        this.securityCode = securityCode;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


