package model.database.pojo;
// Generated Apr 11, 2018 12:54:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usertriplog generated by hbm2java
 */
public class Usertriplog  implements java.io.Serializable {


     private Integer tripLogId;
     private Invoice invoice;
     private Users users;
     private String description;
     private Date modifiedDate;
     private String tripLogStatus;
     private float rating;

    public Usertriplog() {
    }

	
    public Usertriplog(Invoice invoice, Users users, Date modifiedDate, String tripLogStatus, float rating) {
        this.invoice = invoice;
        this.users = users;
        this.modifiedDate = modifiedDate;
        this.tripLogStatus = tripLogStatus;
        this.rating = rating;
    }
    public Usertriplog(Invoice invoice, Users users, String description, Date modifiedDate, String tripLogStatus, float rating) {
       this.invoice = invoice;
       this.users = users;
       this.description = description;
       this.modifiedDate = modifiedDate;
       this.tripLogStatus = tripLogStatus;
       this.rating = rating;
    }
   
    public Integer getTripLogId() {
        return this.tripLogId;
    }
    
    public void setTripLogId(Integer tripLogId) {
        this.tripLogId = tripLogId;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getTripLogStatus() {
        return this.tripLogStatus;
    }
    
    public void setTripLogStatus(String tripLogStatus) {
        this.tripLogStatus = tripLogStatus;
    }
    public float getRating() {
        return this.rating;
    }
    
    public void setRating(float rating) {
        this.rating = rating;
    }




}


