package model.database.pojo;
// Generated Apr 11, 2018 12:54:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Userfacebookaccount generated by hbm2java
 */
public class Userfacebookaccount  implements java.io.Serializable {


     private int userId;
     private Users users;
     private byte[] facebookId;
     private Date modifiedDate;

    public Userfacebookaccount() {
    }

    public Userfacebookaccount(Users users, byte[] facebookId, Date modifiedDate) {
       this.users = users;
       this.facebookId = facebookId;
       this.modifiedDate = modifiedDate;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public byte[] getFacebookId() {
        return this.facebookId;
    }
    
    public void setFacebookId(byte[] facebookId) {
        this.facebookId = facebookId;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


