package model.database.pojo;
// Generated Apr 11, 2018 12:54:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private Role role;
     private byte isGoogleLogin;
     private byte isFacebookLogin;
     private Date modifiedDate;
     private Usergoogleaccount usergoogleaccount;
     private Logininfo logininfo;
     private Userpaymentinfo userpaymentinfo;
     private Userinfo userinfo;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);
     private Set<Specialpromotion> specialpromotions = new HashSet<Specialpromotion>(0);
     private Userfacebookaccount userfacebookaccount;
     private Set<Usertriplog> usertriplogs = new HashSet<Usertriplog>(0);

    public Users() {
    }

	
    public Users(Role role, byte isGoogleLogin, byte isFacebookLogin, Date modifiedDate) {
        this.role = role;
        this.isGoogleLogin = isGoogleLogin;
        this.isFacebookLogin = isFacebookLogin;
        this.modifiedDate = modifiedDate;
    }
    public Users(Role role, byte isGoogleLogin, byte isFacebookLogin, Date modifiedDate, Usergoogleaccount usergoogleaccount, Logininfo logininfo, Userpaymentinfo userpaymentinfo, Userinfo userinfo, Set<Invoice> invoices, Set<Specialpromotion> specialpromotions, Userfacebookaccount userfacebookaccount, Set<Usertriplog> usertriplogs) {
       this.role = role;
       this.isGoogleLogin = isGoogleLogin;
       this.isFacebookLogin = isFacebookLogin;
       this.modifiedDate = modifiedDate;
       this.usergoogleaccount = usergoogleaccount;
       this.logininfo = logininfo;
       this.userpaymentinfo = userpaymentinfo;
       this.userinfo = userinfo;
       this.invoices = invoices;
       this.specialpromotions = specialpromotions;
       this.userfacebookaccount = userfacebookaccount;
       this.usertriplogs = usertriplogs;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public byte getIsGoogleLogin() {
        return this.isGoogleLogin;
    }
    
    public void setIsGoogleLogin(byte isGoogleLogin) {
        this.isGoogleLogin = isGoogleLogin;
    }
    public byte getIsFacebookLogin() {
        return this.isFacebookLogin;
    }
    
    public void setIsFacebookLogin(byte isFacebookLogin) {
        this.isFacebookLogin = isFacebookLogin;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Usergoogleaccount getUsergoogleaccount() {
        return this.usergoogleaccount;
    }
    
    public void setUsergoogleaccount(Usergoogleaccount usergoogleaccount) {
        this.usergoogleaccount = usergoogleaccount;
    }
    public Logininfo getLogininfo() {
        return this.logininfo;
    }
    
    public void setLogininfo(Logininfo logininfo) {
        this.logininfo = logininfo;
    }
    public Userpaymentinfo getUserpaymentinfo() {
        return this.userpaymentinfo;
    }
    
    public void setUserpaymentinfo(Userpaymentinfo userpaymentinfo) {
        this.userpaymentinfo = userpaymentinfo;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }
    public Set<Specialpromotion> getSpecialpromotions() {
        return this.specialpromotions;
    }
    
    public void setSpecialpromotions(Set<Specialpromotion> specialpromotions) {
        this.specialpromotions = specialpromotions;
    }
    public Userfacebookaccount getUserfacebookaccount() {
        return this.userfacebookaccount;
    }
    
    public void setUserfacebookaccount(Userfacebookaccount userfacebookaccount) {
        this.userfacebookaccount = userfacebookaccount;
    }
    public Set<Usertriplog> getUsertriplogs() {
        return this.usertriplogs;
    }
    
    public void setUsertriplogs(Set<Usertriplog> usertriplogs) {
        this.usertriplogs = usertriplogs;
    }




}


